### PR TITLE
Reword README

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by milessabin** [comment]
Yes, I'm mostly in favour of this, but I think you should still mention that it's available in 2.12.0 and TLS 2.11.8 (and soon 2.11.9).

**Comment by adelbertc** [comment]
I did didn't I?

**Comment by adelbertc** [comment]
**EDIT** I realized it was a bit buried so I moved it towards the top, as well as updated the summary to reflect the now merged PR 🎉

**Comment by milessabin** [comment]
That's spot on ... many thanks ... merging :-)

**Pull request merged**
